import type { Trial } from "./types"

export const STATIC_TRIALS: Trial[] = [
  { nct: "NCT03781128", title: "Safety and Efficacy of LSD as Treatment for Cluster Headache — Phase II RCT", status: "RECRUITING", phase: ["PHASE2"], type: "INTERVENTIONAL", sponsor: "University Hospital, Basel, Switzerland", start: "", enrollment: 30, end: "2025-12", interventions: "Lysergic Acid Diethylamide, Placebo", summary: "Double-blind crossover study of 3×100µg LSD vs placebo in episodic/chronic CH.", conditions: "Cluster Headache" },
  { nct: "NCT05477459", title: "Efficacy and Safety of Minidosing LSD for Chronic Cluster Headache", status: "RECRUITING", phase: ["PHASE2"], type: "INTERVENTIONAL", sponsor: "Radboud University Medical Center", start: "", enrollment: 65, end: "2027-04", interventions: "LSD tartrate, Placebo", summary: "Phase 2 RCT of sub-hallucinogenic LSD dosing for chronic CH.", conditions: "Chronic Cluster Headache" },
  { nct: "NCT04814381", title: "KETALGIA: Ketamine + Magnesium Sulfate for Refractory Chronic Cluster Headache", status: "RECRUITING", phase: ["PHASE4"], type: "INTERVENTIONAL", sponsor: "University Hospital, Clermont-Ferrand", start: "", enrollment: 90, end: "2026-09", interventions: "Ketamine + Magnesium sulfate", summary: "Single IV infusion trial. Prior pilot: 13/17 patients had ≥50% attack reduction.", conditions: "Refractory Chronic Cluster Headache" },
  { nct: "NCT06950281", title: "SUNCET: Low Sodium Oxybate for Nocturnal Cluster Headache", status: "NOT_YET_RECRUITING", phase: ["PHASE2"], type: "INTERVENTIONAL", sponsor: "Leiden University Medical Center", start: "", enrollment: 52, end: "2027-12", interventions: "Low Sodium Oxybate, Placebo", summary: "Targets nocturnal CH via sleep deepening (↑SWS, ↓REM). Wearable sleep monitoring.", conditions: "Chronic Cluster Headache" },
  { nct: "NCT06540651", title: "Light Therapy for Chronic Cluster Headache Prevention", status: "RECRUITING", phase: ["NA"], type: "INTERVENTIONAL", sponsor: "Assistance Publique Hopitaux De Marseille", start: "", enrollment: 48, end: "2027-02", interventions: "Luminettes® light therapy", summary: "Proof-of-concept RCT of bright light device for circadian/hypothalamic modulation.", conditions: "Cluster Headache" },
  { nct: "NCT07113470", title: "RESPONSE-II: Combined Trigeminal + Occipital Nerve Stimulation (PRIMUS)", status: "RECRUITING", phase: ["NA"], type: "INTERVENTIONAL", sponsor: "Salvia BioElectronics", start: "", enrollment: 10, end: "2027-04", interventions: "Salvia PRIMUS implantable neurostimulator", summary: "Second human study of implantable dual nerve stimulator.", conditions: "Chronic Cluster Headache" },
  { nct: "NCT05324748", title: "Repeated GON Injections for Chronic Cluster Headache Prevention", status: "RECRUITING", phase: ["PHASE3"], type: "INTERVENTIONAL", sponsor: "Leiden University Medical Center", start: "", enrollment: 50, end: "2025-12", interventions: "Methylprednisolone, Saline", summary: "Phase 3 RCT of repeated greater occipital nerve corticosteroid blocks.", conditions: "Cluster Headache" },
  { nct: "NCT03944876", title: "Botulinum Toxin A Blockade of SPG in Refractory Chronic CH", status: "RECRUITING", phase: ["PHASE3"], type: "INTERVENTIONAL", sponsor: "Norwegian University of Science and Technology", start: "", enrollment: 112, end: "2025-09", interventions: "Botulinum toxin type A, Placebo", summary: "Phase 3 RCT, 5 European sites.", conditions: "Cluster Headache" },
  { nct: "NCT06787677", title: "SPG Pulsed Radiofrequency for Chronic Cluster Headache", status: "RECRUITING", phase: ["NA"], type: "INTERVENTIONAL", sponsor: "Beijing Tiantan Hospital", start: "", enrollment: 108, end: "2029-12", interventions: "Pulsed radiofrequency, Nerve block", summary: "RCT comparing PRF vs nerve block for chronic CH.", conditions: "Cluster Headache" },
  { nct: "NCT04406259", title: "Atrioventricular Block and Cluster Headache (Verapamil Cardiac Safety)", status: "ACTIVE_NOT_RECRUITING", phase: ["PHASE4"], type: "INTERVENTIONAL", sponsor: "Centre Hospitalier Universitaire de Nice", start: "", enrollment: 60, end: "2025-09", interventions: "Verapamil", summary: "Cardiac monitoring study at high verapamil doses.", conditions: "Cluster Headache" },
]
